# 文件名: .github/workflows/generate-snake.yml

name: Generate Contribution Snake

on:
  # 1. 自动执行：每天午夜 (UTC时间) 运行一次
  schedule:
    - cron: "0 0 * * *"
  
  # 2. 手动执行：允许你从 Actions 标签页手动触发此工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1.检出你的仓库代码
      - uses: actions/checkout@v3

      # 2. 关键步骤：使用 Platane/snk action 生成贪吃蛇动画
      - uses: Platane/snk@v3
        with:
          # 你的 GitHub 用户名 (!!! 请确保这里是你的用户名 !!!)
          github_user_name: Michael-Jackson666
          
          # 输出文件的路径。我们生成两个版本：一个亮色，一个暗色
          # outputs: >- 
          #   dist/github-contribution-grid-snake.svg,
          #   dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

        # 3. 提供 GitHub Token 以便 Action 可以推送到你的仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. 将生成的文件推送到一个新的分支 (output)
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
